export const contact = {
  phone: "(65) 99982-2022",
  whatsappHref: "https://wa.me/5565999822022",
  email: "contato@codigo5.com.br",
  address: "R. Três, 2 - Morada do Ouro, Cuiabá - MT, CEP 78053-208",
};

export const clients = [
  {
    name: "PraticLar",
    logo: "/assets/codigo5/clients-extended/praticlar.png",
    segment: "Industria e varejo",
    site: "praticlar.com.br",
    surface: "light",
  },
  {
    name: "Sonata Musical",
    logo: "/assets/codigo5/client-catalog/sonata.webp",
    segment: "Varejo especializado",
    site: "sonatamusical.com.br",
    surface: "light",
    logoClass: "max-h-10",
    frameClass: "bg-[linear-gradient(135deg,#fffdfa,#efe1c4)]",
  },
  {
    name: "Stilo Assessoria",
    logo: "/assets/codigo5/clients-extended/stiloassessoria.webp",
    segment: "Credito e consignado",
    site: "stiloassessoria.com.br",
    surface: "light",
  },
  {
    name: "CREF17/MT",
    logo: "/assets/codigo5/client-catalog/cref17-official.png",
    segment: "Institucional",
    site: "cref17.org.br",
    surface: "light",
    logoClass: "max-h-14",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f0f5fb)]",
  },
  {
    name: "Axis Construcoes",
    logo: "/assets/codigo5/client-catalog/axis-white.png",
    segment: "Construcao civil",
    site: "axisconstrucoes.com.br",
    surface: "dark",
    logoClass: "max-h-11",
    invertOnDark: false,
  },
  {
    name: "Calcario Alianca",
    logo: "/assets/codigo5/clients-extended/calcario-alianca.svg",
    segment: "Industria mineral",
    site: "calcarioalianca.com",
    surface: "sand",
  },
  {
    name: "Clinica Petterle",
    logo: "/assets/codigo5/client-catalog/clinicapetterle-2025.png",
    segment: "Saude",
    site: "clinicapetterle.com.br",
    surface: "light",
    logoClass: "max-h-16",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#eef7f8)]",
  },
  {
    name: "Portal 163",
    logo: "/assets/codigo5/client-catalog/portal163-inline.png",
    segment: "Midia regional",
    site: "portal163.com.br",
    surface: "light",
    logoClass: "max-h-10",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f5f3ef)]",
  },
  {
    name: "Perrengue Mato Grosso",
    logo: "/assets/codigo5/client-catalog/perrengue-2026.png",
    segment: "Midia e entretenimento",
    site: "perrenguematogrosso.com.br",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#fffaf3,#f3e3cc)]",
  },
  {
    name: "AlphaVille Buffet",
    logo: "/assets/codigo5/clients/alphaville.png",
    segment: "Eventos e buffet",
    site: "alphavillebuffet.com.br",
    surface: "dark",
  },
  {
    name: "Fundacao Abrigo Bom Jesus",
    logo: "/assets/codigo5/clients/abrigo.png",
    segment: "Instituicao social",
    site: "abrigobomjesus.com.br",
    surface: "light",
  },
  {
    name: "IFC",
    logo: "/assets/codigo5/client-catalog/ifc-2026.png",
    segment: "Igreja e comunidade",
    site: "igrejafamiliadacruz.com.br",
    surface: "dark",
    logoClass: "max-h-14",
    invertOnDark: false,
  },
  {
    name: "A Folha Livre",
    logo: "/assets/codigo5/client-catalog/afolhalivre.png",
    segment: "Midia regional",
    site: "afolhalivre.com",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f8f2e8)]",
  },
  {
    name: "Portal Pantanal MT",
    logo: "/assets/codigo5/client-catalog/portalpantanalmt.jpg",
    segment: "Jornalismo digital",
    site: "portalpantanalmt.com",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f2f7fb)]",
  },
  {
    name: "Portal Norte MT",
    logo: "/assets/codigo5/client-catalog/portalnortemt.png",
    segment: "Portal editorial",
    site: "portalnortemt.com",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f6f4ef)]",
  },
];

export const portfolioClients = [
  {
    name: "PraticLar",
    segment: "Industria e varejo de limpeza",
    site: "praticlar.com.br",
    logo: "/assets/codigo5/clients-extended/praticlar.png",
    surface: "light",
  },
  {
    name: "Sonata Musical",
    segment: "Instrumentos musicais",
    site: "sonatamusical.com.br",
    logo: "/assets/codigo5/client-catalog/sonata.webp",
    surface: "light",
    logoClass: "max-h-11",
    frameClass: "bg-[linear-gradient(135deg,#fffdfa,#efe1c4)]",
  },
  {
    name: "Stilo Assessoria",
    segment: "Credito consignado",
    site: "stiloassessoria.com.br",
    logo: "/assets/codigo5/clients-extended/stiloassessoria.webp",
    surface: "light",
  },
  {
    name: "CREF17/MT",
    segment: "Conselho profissional",
    site: "cref17.org.br",
    logo: "/assets/codigo5/client-catalog/cref17-official.png",
    surface: "light",
    logoClass: "max-h-14",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f0f5fb)]",
  },
  {
    name: "Axis Construcoes",
    segment: "Construcao civil",
    site: "axisconstrucoes.com.br",
    logo: "/assets/codigo5/client-catalog/axis-white.png",
    surface: "dark",
    logoClass: "max-h-12",
    invertOnDark: false,
  },
  {
    name: "Calcario Alianca",
    segment: "Industria mineral",
    site: "calcarioalianca.com",
    logo: "/assets/codigo5/clients-extended/calcario-alianca.svg",
    surface: "sand",
  },
  {
    name: "Franca & Moraes",
    segment: "Advocacia empresarial",
    site: "francaemoraes.com.br",
    logo: "/assets/codigo5/client-catalog/francaemoraes-topo.png",
    surface: "light",
    logoClass: "max-h-11",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f4efe7)]",
  },
  {
    name: "Nobres Racoes",
    segment: "Nutricao animal",
    site: "nobresracoes.com.br",
    logo: "https://nobresracoes.com.br/app/uploads/2023/12/logo-nr-color-hor.png",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "Usical",
    segment: "Industria e concreto",
    site: "usicalnbs.com.br",
    logo: "https://usicalnbs.com.br/app/uploads/2023/10/logo_pos_azul@2x.png",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "FlechaTur",
    segment: "Turismo e fretamento",
    site: "flechaturmt.com.br",
    logo: "/assets/codigo5/client-catalog/flechatur-official.png",
    surface: "sand",
    logoClass: "max-h-10",
  },
  {
    name: "Instituto Mario Cardi",
    segment: "Saude e instituto",
    site: "institutomariocardi.com.br",
    logo: "/assets/codigo5/client-catalog/mariocardi-blue.webp",
    surface: "light",
    logoClass: "max-h-11",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#eef5fb)]",
  },
  {
    name: "Clinica Petterle",
    segment: "Saude vascular",
    site: "clinicapetterle.com.br",
    logo: "/assets/codigo5/client-catalog/clinicapetterle-2025.png",
    surface: "light",
    logoClass: "max-h-16",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#eef7f8)]",
  },
  {
    name: "Portal 163",
    segment: "Midia regional",
    site: "portal163.com.br",
    logo: "/assets/codigo5/client-catalog/portal163-inline.png",
    surface: "light",
    logoClass: "max-h-10",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f5f3ef)]",
  },
  {
    name: "Regional MT News",
    segment: "Portal de noticias",
    site: "regionalmtnews.com.br",
    logo: "/assets/codigo5/client-catalog/regionalmtnews.webp",
    surface: "dark",
    logoClass: "max-h-12",
  },
  {
    name: "Impacto Geral",
    segment: "Jornalismo digital",
    site: "impactogeral.com.br",
    logo: "/assets/codigo5/client-catalog/impactogeral-inline.png",
    surface: "light",
    logoClass: "max-h-10",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f4f0e8)]",
  },
  {
    name: "O Matogrossense",
    segment: "Portal editorial",
    site: "omatogrossense.com",
    logo: "/assets/codigo5/client-catalog/omatogrossense-inline.webp",
    surface: "light",
    logoClass: "max-h-10",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f7f1e6)]",
  },
  {
    name: "Roo Noticias",
    segment: "Noticias locais",
    site: "roonoticias.com",
    logo: "/assets/codigo5/client-catalog/roonoticias-official.png",
    surface: "light",
    logoClass: "max-h-14",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f3f7fb)]",
  },
  {
    name: "AlphaVille Buffet",
    segment: "Eventos e buffet",
    site: "alphavillebuffet.com.br",
    logo: "/assets/codigo5/clients/alphaville.png",
    surface: "dark",
  },
  {
    name: "Fundacao Abrigo Bom Jesus",
    segment: "Instituicao social",
    site: "abrigobomjesus.com.br",
    logo: "/assets/codigo5/clients/abrigo.png",
    surface: "light",
  },
  {
    name: "Igreja Familia da Cruz",
    segment: "Igreja e comunidade",
    site: "igrejafamiliadacruz.com.br",
    logo: "/assets/codigo5/client-catalog/ifc-2026.png",
    surface: "dark",
    logoClass: "max-h-14",
    invertOnDark: false,
  },
  {
    name: "A Folha Livre",
    segment: "Portal editorial",
    site: "afolhalivre.com",
    logo: "/assets/codigo5/client-catalog/afolhalivre.png",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f8f2e8)]",
  },
  {
    name: "Portal Pantanal MT",
    segment: "Jornalismo digital",
    site: "portalpantanalmt.com",
    logo: "/assets/codigo5/client-catalog/portalpantanalmt.jpg",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f2f7fb)]",
  },
  {
    name: "Portal Norte MT",
    segment: "Portal editorial",
    site: "portalnortemt.com",
    logo: "/assets/codigo5/client-catalog/portalnortemt.png",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#f6f4ef)]",
  },
];

const extraProofClients = [
  {
    name: "Roo Noticias",
    logo: "/assets/codigo5/client-catalog/roonoticias-official.png",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#eef4ff)]",
  },
  {
    name: "Shop10",
    logo: "/assets/codigo5/clients/shop10.webp",
    surface: "light",
    logoClass: "max-h-12",
    frameClass: "bg-[linear-gradient(135deg,#ffffff,#eef4ff)]",
  },
];

const proofClientCatalog = [...portfolioClients, ...clients, ...extraProofClients].filter(
  (client, index, array) => index === array.findIndex((item) => item.name === client.name),
);

export const homeAnchorClients = [
  "Perrengue Mato Grosso",
  "Roo Noticias",
  "Portal Pantanal MT",
  "Portal Norte MT",
  "Shop10",
  "AlphaVille Buffet",
].map((name) => proofClientCatalog.find((client) => client.name === name)).filter(Boolean);

export const supportingProofClients = proofClientCatalog.filter(
  (client) => !homeAnchorClients.some((anchorClient) => anchorClient.name === client.name),
);

export const services = [
  {
    name: "Sites institucionais",
    description: "Mais clareza, confiança e presença comercial melhor resolvida.",
    image: "/assets/codigo5/cases/clinicapetterle-home.png",
    items: ["Marca", "Clareza", "Contato"],
  },
  {
    name: "Lojas virtuais",
    description: "Loja virtual com estrutura para vender sem parecer improvisada.",
    image: "/assets/codigo5/cases/sonatamusical-home.png",
    items: ["Catalogo", "Checkout", "Campanha"],
  },
  {
    name: "SEO e conteudo",
    description: "Mais contexto, mais busca qualificada e mais autoridade.",
    image: "/assets/codigo5/cases/roonoticias-home.png",
    items: ["Busca", "Blog", "Autoridade"],
  },
  {
    name: "Automacoes e IA",
    description: "Atendimento, operação e rotina digital mais conectados.",
    image: "/assets/codigo5/generated/automation-operation-cover.svg",
    items: ["WhatsApp", "Fluxos", "IA"],
  },
];

export const methodologies = [
  {
    name: "Oferta clara",
    detail: "O cliente entende rapido o que a empresa entrega.",
    logos: ["/assets/codigo5/tools/googleanalytics.svg", "/assets/codigo5/tools/googlesearchconsole.svg"],
  },
  {
    name: "Estrutura certa",
    detail: "Site, paginas e blog com navegacao simples.",
    logos: ["/assets/codigo5/tools/wordpress.svg", "/assets/codigo5/tools/cloudflare.svg"],
  },
  {
    name: "Projeto no ar",
    detail: "Tudo entra online com visual forte e leitura leve.",
    logos: ["/assets/codigo5/tools/woocommerce.svg", "/assets/codigo5/tools/elementor.svg"],
  },
  {
    name: "Escala e automacao",
    detail: "Atendimento e rotina conectados quando a operacao pede.",
    logos: ["/assets/codigo5/tools/n8n.svg", "/assets/codigo5/tools/openai.svg"],
  },
];

export const toolLogos = [
  { name: "WordPress", logo: "/assets/codigo5/tools/wordpress.svg" },
  { name: "WooCommerce", logo: "/assets/codigo5/tools/woocommerce.svg" },
  { name: "Elementor", logo: "/assets/codigo5/tools/elementor.svg" },
  { name: "Cloudflare", logo: "/assets/codigo5/tools/cloudflare.svg" },
  { name: "n8n", logo: "/assets/codigo5/tools/n8n.svg" },
  { name: "OpenAI", logo: "/assets/codigo5/tools/openai.svg" },
  { name: "Analytics", logo: "/assets/codigo5/tools/googleanalytics.svg" },
  { name: "Search Console", logo: "/assets/codigo5/tools/googlesearchconsole.svg" },
];

export const useCases = [
  {
    title: "Midia e portais",
    summary: "Home forte, leitura rápida e publicação contínua para audiência regional.",
    image: "/assets/codigo5/cases/roonoticias-home.png",
    points: ["Portal", "Editorial", "Performance"],
  },
  {
    title: "Clinicas e saude",
    summary: "Mais confiança, mais contexto de serviço e menos ruído no atendimento.",
    image: "/assets/codigo5/cases/clinicapetterle-home.png",
    points: ["Agenda", "Google Maps", "SEO local"],
  },
  {
    title: "Varejo e catalogo",
    summary: "Catálogo, contato e jornada digital mais organizada para vender melhor.",
    image: "/assets/codigo5/cases/sonatamusical-home.png",
    points: ["Catalogo", "WhatsApp", "Campanhas"],
  },
];

export const trustNumbers = [
  { label: "Anos de mercado", value: "15+" },
  { label: "Marcas no portifolio", value: "40+" },
  { label: "Segmentos atendidos", value: "10+" },
  { label: "Base local", value: "Cuiaba" },
];
