export const contact = {
  phone: "(65) 99982-2022",
  whatsappHref: "https://wa.me/5565999822022",
  email: "contato@codigo5.com.br",
  address: "R. Três, 2 - Morada do Ouro, Cuiabá - MT, CEP 78053-208",
};

export const clients = [
  {
    name: "PraticLar",
    logo: "/assets/codigo5/clients-extended/praticlar.png",
    segment: "Industria e varejo",
    site: "praticlar.com.br",
    surface: "light",
  },
  {
    name: "Sonata Musical",
    logo: "/assets/codigo5/logos/logo-dark.webp",
    segment: "Varejo especializado",
    site: "sonatamusical.com.br",
    surface: "light",
  },
  {
    name: "Stilo Assessoria",
    logo: "/assets/codigo5/clients-extended/stiloassessoria.webp",
    segment: "Credito e consignado",
    site: "stiloassessoria.com.br",
    surface: "light",
  },
  {
    name: "CREF17/MT",
    logo: "/assets/codigo5/clients-extended/cref17.png",
    segment: "Institucional",
    site: "cref17.org.br",
    surface: "light",
  },
  {
    name: "Axis Construcoes",
    logo: "/assets/codigo5/clients-extended/axis.png",
    segment: "Construcao civil",
    site: "axisconstrucoes.com.br",
    surface: "light",
  },
  {
    name: "Calcario Alianca",
    logo: "/assets/codigo5/clients-extended/calcario-alianca.svg",
    segment: "Industria mineral",
    site: "calcarioalianca.com",
    surface: "sand",
  },
  {
    name: "Clinica Petterle",
    logo: "/assets/codigo5/client-catalog/clinicapetterle.png",
    segment: "Saude",
    site: "clinicapetterle.com.br",
    surface: "light",
    logoClass: "max-h-11",
  },
  {
    name: "Portal 163",
    logo: "/assets/codigo5/client-catalog/portal163.png",
    segment: "Midia regional",
    site: "portal163.com.br",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "Perrengue Mato Grosso",
    logo: "https://cdn.perrenguematogrosso.com/app/uploads/2026/02/perrengue-mt-logo-color%402x-2.png",
    segment: "Midia e entretenimento",
    site: "perrenguematogrosso.com.br",
    surface: "light",
  },
  {
    name: "AlphaVille Buffet",
    logo: "/assets/codigo5/clients/alphaville.png",
    segment: "Eventos e buffet",
    site: "alphavillebuffet.com.br",
    surface: "dark",
  },
  {
    name: "Fundacao Abrigo Bom Jesus",
    logo: "/assets/codigo5/clients/abrigo.png",
    segment: "Instituicao social",
    site: "abrigobomjesus.com.br",
    surface: "light",
  },
  {
    name: "IFC",
    logo: "/assets/codigo5/client-catalog/ifc.png",
    segment: "Igreja e comunidade",
    site: "igrejafamiliadacruz.com.br",
    surface: "light",
    logoClass: "max-h-14",
  },
];

export const portfolioClients = [
  {
    name: "PraticLar",
    segment: "Industria e varejo de limpeza",
    site: "praticlar.com.br",
    logo: "/assets/codigo5/clients-extended/praticlar.png",
    surface: "light",
  },
  {
    name: "Sonata Musical",
    segment: "Instrumentos musicais",
    site: "sonatamusical.com.br",
    logo: "/assets/codigo5/logos/logo-dark.webp",
    surface: "light",
  },
  {
    name: "Stilo Assessoria",
    segment: "Credito consignado",
    site: "stiloassessoria.com.br",
    logo: "/assets/codigo5/clients-extended/stiloassessoria.webp",
    surface: "light",
  },
  {
    name: "CREF17/MT",
    segment: "Conselho profissional",
    site: "cref17.org.br",
    logo: "/assets/codigo5/clients-extended/cref17.png",
    surface: "light",
  },
  {
    name: "Axis Construcoes",
    segment: "Construcao civil",
    site: "axisconstrucoes.com.br",
    logo: "/assets/codigo5/clients-extended/axis.png",
    surface: "light",
  },
  {
    name: "Calcario Alianca",
    segment: "Industria mineral",
    site: "calcarioalianca.com",
    logo: "/assets/codigo5/clients-extended/calcario-alianca.svg",
    surface: "sand",
  },
  {
    name: "Franca & Moraes",
    segment: "Advocacia empresarial",
    site: "francaemoraes.com.br",
    logo: "/assets/codigo5/client-catalog/francaemoraes.webp",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "Nobres Racoes",
    segment: "Nutricao animal",
    site: "nobresracoes.com.br",
    logo: "https://nobresracoes.com.br/app/uploads/2023/12/logo-nr-color-hor.png",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "Usical",
    segment: "Industria e concreto",
    site: "usicalnbs.com.br",
    logo: "https://usicalnbs.com.br/app/uploads/2023/10/logo_pos_azul@2x.png",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "FlechaTur",
    segment: "Turismo e fretamento",
    site: "flechaturmt.com.br",
    logo: "/assets/codigo5/client-catalog/flechatur.png",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "Instituto Mario Cardi",
    segment: "Saude e instituto",
    site: "institutomariocardi.com.br",
    logo: "/assets/codigo5/client-catalog/mariocardi.webp",
    surface: "light",
    logoClass: "max-h-14",
  },
  {
    name: "Clinica Petterle",
    segment: "Saude vascular",
    site: "clinicapetterle.com.br",
    logo: "/assets/codigo5/client-catalog/clinicapetterle.png",
    surface: "light",
    logoClass: "max-h-11",
  },
  {
    name: "Portal 163",
    segment: "Midia regional",
    site: "portal163.com.br",
    logo: "/assets/codigo5/client-catalog/portal163.png",
    surface: "light",
    logoClass: "max-h-16",
  },
  {
    name: "Regional MT News",
    segment: "Portal de noticias",
    site: "regionalmtnews.com.br",
    logo: "/assets/codigo5/client-catalog/regionalmtnews.webp",
    surface: "dark",
    logoClass: "max-h-12",
  },
  {
    name: "Impacto Geral",
    segment: "Jornalismo digital",
    site: "impactogeral.com.br",
    logo: "/assets/codigo5/client-catalog/impactogeral.png",
    surface: "light",
    logoClass: "max-h-15",
  },
  {
    name: "O Matogrossense",
    segment: "Portal editorial",
    site: "omatogrossense.com",
    logo: "/assets/codigo5/client-catalog/omatogrossense.webp",
    surface: "dark",
    logoClass: "max-h-10",
  },
  {
    name: "Roo Noticias",
    segment: "Noticias locais",
    site: "roonoticias.com",
    logo: "/assets/codigo5/client-catalog/roonoticias.png",
    surface: "dark",
    logoClass: "max-h-12",
  },
  {
    name: "AlphaVille Buffet",
    segment: "Eventos e buffet",
    site: "alphavillebuffet.com.br",
    logo: "/assets/codigo5/clients/alphaville.png",
    surface: "dark",
  },
  {
    name: "Fundacao Abrigo Bom Jesus",
    segment: "Instituicao social",
    site: "abrigobomjesus.com.br",
    logo: "/assets/codigo5/clients/abrigo.png",
    surface: "light",
  },
  {
    name: "Igreja Familia da Cruz",
    segment: "Igreja e comunidade",
    site: "igrejafamiliadacruz.com.br",
    logo: "/assets/codigo5/client-catalog/ifc.png",
    surface: "light",
    logoClass: "max-h-16",
  },
];

export const services = [
  {
    name: "Sites institucionais",
    description: "Pagina clara para apresentar, provar e receber contato.",
    image: "/assets/codigo5/blog/site-clientes.webp",
    items: ["Apresentacao", "Contato", "Google Maps"],
  },
  {
    name: "Lojas virtuais",
    description: "Loja pronta para campanha, catalogo e pedido.",
    image: "/assets/codigo5/blog/ia-sites.webp",
    items: ["Catalogo", "Checkout", "Campanhas"],
  },
  {
    name: "SEO e conteudo",
    description: "Conteudo que ajuda o cliente a encontrar e entender.",
    image: "/assets/codigo5/blog/metodologia.webp",
    items: ["SEO local", "Blog", "Pautas"],
  },
  {
    name: "Automacoes e IA",
    description: "Atendimento e operacao mais rapidos, com menos retrabalho.",
    image: "/assets/codigo5/logos/hero-ai.webp",
    items: ["WhatsApp", "Integracoes", "Fluxos"],
  },
];

export const methodologies = [
  {
    name: "1. Clareza da oferta",
    detail: "O cliente precisa entender rapido o que voce vende.",
    logos: ["/assets/codigo5/tools/googleanalytics.svg", "/assets/codigo5/tools/googlesearchconsole.svg"],
  },
  {
    name: "2. Estrutura certa",
    detail: "Site, pagina e blog organizados para navegar sem atrito.",
    logos: ["/assets/codigo5/tools/wordpress.svg", "/assets/codigo5/tools/cloudflare.svg"],
  },
  {
    name: "3. Projeto no ar",
    detail: "Tudo entra online com visual forte e leitura simples.",
    logos: ["/assets/codigo5/tools/woocommerce.svg", "/assets/codigo5/tools/elementor.svg"],
  },
  {
    name: "4. Escala e automacao",
    detail: "Atendimento, conteudo e rotina conectados quando faz sentido.",
    logos: ["/assets/codigo5/tools/n8n.svg", "/assets/codigo5/tools/openai.svg"],
  },
];

export const toolLogos = [
  { name: "WordPress", logo: "/assets/codigo5/tools/wordpress.svg" },
  { name: "WooCommerce", logo: "/assets/codigo5/tools/woocommerce.svg" },
  { name: "Elementor", logo: "/assets/codigo5/tools/elementor.svg" },
  { name: "Cloudflare", logo: "/assets/codigo5/tools/cloudflare.svg" },
  { name: "n8n", logo: "/assets/codigo5/tools/n8n.svg" },
  { name: "OpenAI", logo: "/assets/codigo5/tools/openai.svg" },
  { name: "Analytics", logo: "/assets/codigo5/tools/googleanalytics.svg" },
  { name: "Search Console", logo: "/assets/codigo5/tools/googlesearchconsole.svg" },
];

export const useCases = [
  {
    title: "Bicicletas e bikes eletricas",
    summary: "Loja, catalogo e pauta para um mercado em expansao.",
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=80",
    points: ["Loja", "E-bike", "Pos-venda"],
  },
  {
    title: "Clinicas e saude",
    summary: "Agenda, presenca local e contato simples pelo WhatsApp.",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    points: ["Agenda", "Google Maps", "SEO local"],
  },
  {
    title: "Varejo e ecommerce",
    summary: "Campanhas, categorias e operacao mais agil para vender.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=80",
    points: ["Campanhas", "CRM", "Recuperacao"],
  },
];

export const trustNumbers = [
  { label: "Experiencia", value: "15+ anos" },
  { label: "Sites mapeados", value: "40+ ativos" },
  { label: "Segmentos ativos", value: "10 frentes" },
  { label: "Base local", value: "Cuiaba - MT" },
];
