// Visuals pair a concrete business situation with the original project evidence.
export const automationVisuals = [
  { id: "atendimento", alt: "Profissional atende um cliente em uma barbearia", image: "/assets/codigo5/automacoes/atendimento-humanizado-opt.webp", caption: "Cena ilustrativa criada com IA.", audience: "Negócios que recebem clientes pelo WhatsApp", steps: ["O cliente pergunta", "A IA consulta suas informações", "Sua equipe assume quando precisa"] },
  { id: "agenda", alt: "Recepcionista conversa com uma cliente no balcão de uma clínica", image: "/assets/codigo5/visual/agenda-atendimento.webp", caption: "Cena ilustrativa criada com IA.", audience: "Barbearias, oficinas e consultórios", steps: ["Consulta de horários", "Escolha do cliente", "Confirmação e lembrete"] },
  { id: "pesquisa", alt: "Painel do Radar com referências e fontes de pesquisa", image: "/assets/codigo5/automacoes/radar-fontes-opt.webp", caption: "Radar: captura histórica com dados anonimizados.", audience: "Redações e equipes de comunicação", steps: ["Fontes reunidas", "Assuntos selecionados", "Referências para conferir"] },
  { id: "redes-sociais", alt: "Página do Portal 163 com notícias e conteúdo local", image: "/assets/codigo5/cases/portal163-2026-09-opt.webp", caption: "Portal 163: exemplo de canal editorial do portfólio.", audience: "Portais e equipes que acompanham redes sociais", steps: ["Perfis e temas definidos", "Vídeos e referências organizados", "Seleção pela equipe"] },
  { id: "conteudo", alt: "Painel de preparação e revisão de conteúdo editorial", image: "/assets/codigo5/automacoes/producao-editorial-opt.webp", caption: "Painel editorial: simulação histórica com dados anonimizados.", audience: "Quem produz textos, imagens, áudios e vídeos", steps: ["Fonte identificada", "Material preparado", "Revisão antes de publicar"] },
  { id: "distribuicao", alt: "Notícias publicadas na página do Regional MT News", image: "/assets/codigo5/cases/regional-site-20260909.webp", caption: "Regional MT News: exemplo de publicação do portfólio.", audience: "Empresas que publicam em mais de um canal", steps: ["Conteúdo aprovado", "Formato adaptado", "Envio acompanhado"] },
  { id: "gestao", alt: "Lojista acompanha pedidos no computador ao lado dos produtos", image: "/assets/codigo5/visual/loja-pedidos.webp", caption: "Cena ilustrativa criada com IA.", audience: "Lojas e equipes comerciais e administrativas", steps: ["Dados conectados", "Informações em uma tela", "Pendências à vista"] },
];
